from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class UiWalletWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.accountNameLabel = QLabel(self.centralwidget)
        self.accountNameLabel.setObjectName(u"accountNameLabel")
        self.accountNameLabel.setGeometry(QRect(300, 50, 211, 31))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.accountNameLabel.setFont(font)
        self.accountNameLabel.setScaledContents(False)
        self.accountNameLabel.setAlignment(Qt.AlignCenter)
        self.addressLabel = QLabel(self.centralwidget)
        self.addressLabel.setObjectName(u"addressLabel")
        self.addressLabel.setGeometry(QRect(300, 90, 211, 31))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(False)
        font1.setWeight(50)
        self.addressLabel.setFont(font1)
        self.addressLabel.setScaledContents(False)
        self.addressLabel.setAlignment(Qt.AlignCenter)
        self.balanceLabel = QLabel(self.centralwidget)
        self.balanceLabel.setObjectName(u"balanceLabel")
        self.balanceLabel.setGeometry(QRect(220, 130, 371, 81))
        font2 = QFont()
        font2.setPointSize(22)
        font2.setBold(True)
        font2.setWeight(75)
        self.balanceLabel.setFont(font2)
        self.balanceLabel.setScaledContents(False)
        self.balanceLabel.setAlignment(Qt.AlignCenter)
        self.copyBT = QPushButton(self.centralwidget)
        self.copyBT.setObjectName(u"copyBT")
        self.copyBT.setGeometry(QRect(478, 86, 41, 36))
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(610, 46, 171, 37))
        self.importBT = QPushButton(self.centralwidget)
        self.importBT.setObjectName(u"importBT")
        self.importBT.setGeometry(QRect(660, 130, 121, 36))
        self.createBT = QPushButton(self.centralwidget)
        self.createBT.setObjectName(u"createBT")
        self.createBT.setGeometry(QRect(660, 90, 121, 36))
        self.lockBT = QPushButton(self.centralwidget)
        self.lockBT.setObjectName(u"lockBT")
        self.lockBT.setGeometry(QRect(10, 47, 103, 36))
        self.showRegistersBT = QPushButton(self.centralwidget)
        self.showRegistersBT.setObjectName(u"showRegistersBT")
        self.showRegistersBT.setGeometry(QRect(340, 300, 121, 36))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(340, 350, 121, 36))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        from . import UiLoginWindow, UiImportAccountWindow, UiCreateAccountWindow
        self.lockBT.clicked.connect(lambda: UiLoginWindow().setupUi(MainWindow))
        self.copyBT.clicked.connect(lambda: 1)
        self.importBT.clicked.connect(lambda: UiImportAccountWindow().setupUi(MainWindow))
        self.createBT.clicked.connect(lambda: UiCreateAccountWindow().setupUi(MainWindow))
        self.comboBox.currentIndexChanged.connect(lambda: self.accountNameLabel.setText(self.comboBox.currentText()))

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Document Registrar", None))
        self.accountNameLabel.setText(QCoreApplication.translate("MainWindow", u"Account Name 1", None))
        self.addressLabel.setText(QCoreApplication.translate("MainWindow", u"0x77c1...a77F", None))
        self.balanceLabel.setText(QCoreApplication.translate("MainWindow", u"73.0132 ETH", None))
        self.copyBT.setText(QCoreApplication.translate("MainWindow", u"copy", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Account Name 1", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Account Name 2", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Account Name 3", None))

        self.importBT.setText(QCoreApplication.translate("MainWindow", u"Import Account", None))
        self.createBT.setText(QCoreApplication.translate("MainWindow", u"Create Account", None))
        self.lockBT.setText(QCoreApplication.translate("MainWindow", u"Lock", None))
        self.showRegistersBT.setText(QCoreApplication.translate("MainWindow", u"register a file", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"show registers", None))
    # retranslateUi
